### ISSUE TITLE
Exception thrown at getRestrictionHeaderDates

### ISSUE THREAD

**Issue by daxu7509** [open-track/jpaf#3]
hi,
I downloaded your engine and used your DTD2Mysql to create database. 
However, when the engine starts, it throws exception from createCalendarRestriction, basically tables such as restriction_header_date doesn't have expected columns "start_date" or "end_date". Instead, it has "date_from" and "date_to".

Also these columns are char[4], (e.g. 0620), so not the normal datetime column. which will throw exception if these values were passed to LocalDate functions.

Am I using a wrong version of DTD2Mysql? I downloaded from latest master branch.

Many Thanks

**Comment by linusnorton** [comment]
I think you need to run `dtd2mysql --fares-clean`

**Comment by daxu7509** [comment]
Hi,
I actually deleted the whole database and reimported the data. It gives me the same problem.
Reading the spec, apparently restriction_header_date should have columns "date_from" and "date_to" and should be char(4).

So I think dtd2mysql done the job correctly, it is the engine code's bug as it always expect start_date and end_date which a normal date?

**Comment by linusnorton** [comment]
You need to run both `dtd2mysql --fares file.zip` and `dtd2mysql --fares-clean`

**Comment by linusnorton** [comment]
in fact, as of yesterday you can now just run `npm run data` and it should do absolutely everything for you

**Comment by daxu7509** [comment]
ok, i will try this bit later

**Comment by daxu7509** [comment]
[2017-10-14T20:39:38.490Z] INFO (942 on DESKTOP-7PNT2SJ): Loading locations, routes, validity and restrictions
{ NullPointerException
    at requireNonNull (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/js-joda/dist/js-joda.js:110:15)
    at DateTimeFormatter.parse2 (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/js-joda/dist/js-joda.js:2288:36)
    at DateTimeFormatter.parse (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/js-joda/dist/js-joda.js:2270:25)
    at Function.parse (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/js-joda/dist/js-joda.js:871:26)
    at RestrictionRepository.createRestrictionDate (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/gb-rail-fares/dist/src/restriction/repository/RestrictionRepository.js:111:74)
    at RestrictionRepository.createCalendarRestriction (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/gb-rail-fares/dist/src/restriction/repository/RestrictionRepository.js:123:120)
    at db.query.map.row (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/gb-rail-fares/dist/src/restriction/repository/RestrictionRepository.js:119:30)
    at tryCatcher (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/mnt/c/Users/daxu/Downloads/jpaf-masternew/jpaf-master/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) message: 'text must not be null' }
(node:942) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'start' of undefined
(node:942) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by daxu7509** [comment]
hi,
It still gives me the same error as before (as the code still expects start_date, but the database has date_from, also char(4) issue is still there)

**Comment by linusnorton** [comment]
If that column is null then the database hasn't been set up correctly. There are two separate commands in the dtd2mysql tool, the --fares command imports the feed in a fairly raw form, then the --clean-fares will remove some old data and populate that column.

**Comment by daxu7509** [comment]
the problem is not about null column, it is about the column name is wrong. You are looking a column called start_date, but the table has column date_from. As a result, the RestrictionRepository.js throws exception

**Comment by daxu7509** [comment]
the db schema is not compatible with the nodejs code, that is the problem, not data quality.

**Comment by daxu7509** [comment]
For example, following code returns data from restriction_time_date and then call createRestrictionDate for each row. 
In function createRestrictionDate, we can see that it expects start_date and end_date.
However, restriction_time_date table doesn't have these columns (it has date_from and date_to)

 getTimeRestrictionDates(timeRestriction) {
        return this.db
            .query(`
        SELECT * FROM restriction_time_date 
        WHERE restriction_code = ? 
        AND cf_mkr = ?
        AND out_ret = ?
        AND sequence_no = ?
      `, [timeRestriction.restriction_code, timeRestriction.cf_mkr, timeRestriction.out_ret, timeRestriction.sequence_no])
            .map(this.createRestrictionDate);
    }

createRestrictionDate(row) {
        return new RestrictionDate_1.RestrictionDate(js_joda_1.LocalDate.parse(row.start_date), js_joda_1.LocalDate.parse(row.end_date), row.cf_mkr, row.monday === 1, row.tuesday === 1, row.wednesday === 1, row.thursday === 1, row.friday === 1, row.saturday === 1, row.sunday === 1);
    }

**Comment by linusnorton** [comment]
Running that command I mentioned adds those columns
